import type { TColorPalette, THexColor } from "@/types/colors";

export default function terminal(palette: TColorPalette): { [key: string]: THexColor } {
  return {
    "panel.background": palette.background,
    "panelSection.border": palette.comments,
    "panel.border": palette.yellow,
    "panelTitle.activeBorder": palette.red,
    "panelTitle.activeForeground": palette.foreground,
    "panelTitle.inactiveForeground": palette.comments,
    "badge.background": palette.yellow,
    "badge.foreground": palette.background,
    "terminal.foreground": palette.foreground,
    "terminal.selectionBackground": "#ffffff40",
    "terminalCursor.background": palette.transparent,
    "terminalCursor.foreground": "#ff0000",
    "terminal.border": palette.comments,
    "terminal.ansiBlack": "#080808",
    "terminal.ansiBlue": "#2472c8",
    "terminal.ansiBrightBlack": "#666666",
    "terminal.ansiBrightBlue": "#3b8eea",
    "terminal.ansiBrightCyan": "#29b8db",
    "terminal.ansiBrightGreen": "#23d18b",
    "terminal.ansiBrightMagenta": "#d670d6",
    "terminal.ansiBrightRed": "#f14c4c",
    "terminal.ansiBrightWhite": "#e5e5e5",
    "terminal.ansiBrightYellow": "#f5f543",
    "terminal.ansiCyan": "#11a8cd",
    "terminal.ansiGreen": "#0dbc79",
    "terminal.ansiMagenta": "#bc3fbc",
    "terminal.ansiRed": "#cd3131",
    "terminal.ansiWhite": "#e5e5e5",
    "terminal.ansiYellow": "#e5e510",
  };
}
